### ISSUE TITLE
Bug when using `evalues.HR()` in recent R versions?

### ISSUE THREAD

**Issue by R-Walmsley** [cran/EValue#1]
Hi, 

Thanks for the really useful package!

I think I might have spotted a bug when using `evalues.HR` in R 4.2.0. When I run the example, I get an error: 
```
evalues.HR(0.56, 0.46, 0.69, rare = FALSE)
**Error in as.data.frame.default(y) : 
  cannot coerce class ‘c("RR", "estimate")’ to a data.frame**
```

I think this is to do with a change in R between R version 4.1.0 (as the same code ran fine there) and R version 4.2.0. 

It's also particular to `evalues.HR`, as `evalues.RR` runs fine.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by R-Walmsley** [comment]
Sorry, thanks!
